# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(288, 222)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.select_function_label = QtWidgets.QLabel(self.centralwidget)
        self.select_function_label.setGeometry(QtCore.QRect(30, 10, 101, 31))
        self.select_function_label.setObjectName("select_function_label")
        self.func_select_certain_button = QtWidgets.QPushButton(self.centralwidget)
        self.func_select_certain_button.setGeometry(QtCore.QRect(100, 140, 81, 31))
        self.func_select_certain_button.setObjectName("func_select_certain_button")
        self.data_filter_button = QtWidgets.QRadioButton(self.centralwidget)
        self.data_filter_button.setGeometry(QtCore.QRect(31, 51, 118, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.data_filter_button.setFont(font)
        self.data_filter_button.setObjectName("data_filter_button")
        self.func_merge_button = QtWidgets.QRadioButton(self.centralwidget)
        self.func_merge_button.setGeometry(QtCore.QRect(110, 110, 99, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.func_merge_button.setFont(font)
        self.func_merge_button.setObjectName("func_merge_button")
        self.inv_download_button = QtWidgets.QRadioButton(self.centralwidget)
        self.inv_download_button.setGeometry(QtCore.QRect(155, 51, 99, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inv_download_button.setFont(font)
        self.inv_download_button.setObjectName("inv_download_button")
        self.inv_data_process_button = QtWidgets.QRadioButton(self.centralwidget)
        self.inv_data_process_button.setGeometry(QtCore.QRect(31, 80, 99, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inv_data_process_button.setFont(font)
        self.inv_data_process_button.setObjectName("inv_data_process_button")
        self.combo_split_button = QtWidgets.QRadioButton(self.centralwidget)
        self.combo_split_button.setGeometry(QtCore.QRect(155, 80, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.combo_split_button.setFont(font)
        self.combo_split_button.setObjectName("combo_split_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 288, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.select_function_label.setText(_translate("MainWindow", "功能选择"))
        self.func_select_certain_button.setText(_translate("MainWindow", "确认"))
        self.data_filter_button.setText(_translate("MainWindow", "原始表处理"))
        self.func_merge_button.setText(_translate("MainWindow", "全选"))
        self.inv_download_button.setText(_translate("MainWindow", "库存下载"))
        self.inv_data_process_button.setText(_translate("MainWindow", "库存处理"))
        self.combo_split_button.setText(_translate("MainWindow", "Combo拆分"))
